language: ruby
rvm: 2.5.5

# we need MySQL 5.7+ to support JSON aggregation
dist: xenial

addons:
  # Rails 6 requires Postgres 9.3+
  # We need Postgres 9.4+ to support JSON aggregation
  postgresql: "9.4"

services:
  - postgresql
  - mysql

# Test on supported versions of Rails + Edge Rails
# (When Rails 6.0 is released, drop Rails 4.2)
matrix:
  include:
  - gemfile: gemfiles/rails_4.2.gemfile
  - gemfile: gemfiles/rails_5.0.gemfile
  - gemfile: gemfiles/rails_5.1.gemfile
  - gemfile: gemfiles/rails_5.2.gemfile
  - gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
  - gemfile: gemfiles/rails_edge.gemfile
