language: ruby
rvm: 2.5.5

# Test on supported versions of Rails + Edge Rails
# (When Rails 6.0 is released, drop Rails 4.2)
matrix:
  include:
  - gemfile: gemfiles/rails_4.2.gemfile
  - gemfile: gemfiles/rails_5.0.gemfile
  - gemfile: gemfiles/rails_5.1.gemfile
  - gemfile: gemfiles/rails_5.2.gemfile
  - gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
  - gemfile: gemfiles/rails_edge.gemfile
